language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - git clone https://github.com/fukamachi/clack ~/lisp/clack
  - git clone https://github.com/fukamachi/ningle ~/lisp/ningle

script:
  - cl -l prove -e '(or (prove:run :caveman2-test) (uiop:quit -1))'
